version: '3.9'

services:
  redis-server:
    container_name: 'redis_server'
    image: 'redis'

  node-app:
    container_name: 'node-app'
    build:
      context: .
      dockerfile: 'Dockerfile.node'
    ports:
      - "8081:8081"
